spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forum
    username: root
    password: example
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: asd123